resilience4j:
  circuitbreaker:
    configs:
      my-default-config-circuit-breaker:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      items:
        base-config: my-default-config-circuit-breaker
  timelimiter:
    configs:
      my-default-config-time-limiter:
        timeout-duration: 3s
    instances:
      items:
        base-config: my-default-config-time-limiter




